sudo: false
language: python
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libopenblas-dev
python:
  - "3.6"
  - "3.7"
script:
    - python ./np-bench setup
    - python ./np-bench run > all.log
    - python ./np-bench run -tpythran > pythran.log
    - python ./np-bench run -tnumba benchmarks/arc_distance.py > numba.log
    - python ./np-bench format -t png all.log
    - python ./np-bench format -t tex pythran.log
    - python ./np-bench format -t rst numba.log
    - sort all.log


