sudo: false
language: python
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - libopenblas-dev

python:
  - "3.6"
  - "3.7"

install:
    - pip install -r requirements.txt
    - python setup.py install

script:
    - np-bench list
    - np-bench run -o all.log
    - np-bench run -tpythran > pythran.log
    - np-bench run -tnumba benchmarks/arc_distance.py -o numba.log
    - np-bench format -t png all.log
    - np-bench format -t tex pythran.log
    - np-bench format -t rst numba.log
    - sort all.log
